services:
  - type: web
    name: wingxtra-cloud-gcs
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: build
    pullRequestPreviewsEnabled: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
